SCOREBOARD_TITLE: "&6Mango Revival&7(Map 1)"
FACTION_STUCK: "&cStuck Teleport &8»&7"
FACTION_HOME: "&cStuck Teleport &8»&7"
ROOT_NODE: "mango" #nodes will be like mango.setdtr, or whatever you said root_node to be
ALLY_REQUEST_TIMEOUT: 30
DTR_SPEED: 60 #This is how long it will take (in seconds) for a faction to regen 0.1 dtr
MAX_ALLIES: 1
DTR_PER_PLAYER: 1.1
MAX_DTR: 5.5
START_BALANCE: 0
MAX_PLAYERS: 30
MAX_NAME_LENGTH: 12
MIN_NAME_LENGTH: 3
OFFLINE_COLOR: "&c"
ONLINE_COLOR: "&a"
RAIDABLE_COLOR: "&c"
RAIDABLE_SYMBOL: " &c"
NOT_RAIDABLE_COLOR: "&a"
NOT_RAIDABLE_SYMBOL: "&a"
REGEN_COLOR: "&a"
REGEN_SYMBOL: "&a"
FROZEN_COLOR: "&e"
FROZEN_SYMBOL: "&e"
FREEZE_DURATION: 3600 #in seconds, default is one hour.
TELEPORT_COOLDOWN:
  HOME: 10
  STUCK: 60
CHAT_PREFIX:
  ENABLED: true
  NO_FACTION: "&e[&c-&e] &r"
  FRIENDLY_FACTION: "&e[&a{faction}&e]&r "
  ALLY_FACTION: "&e[&d{faction}&e] &r"
  ENEMY_FACTION: "&e[&c{faction}&e] &r"
WILDERNESS:
  NAME: "&7Wilderness"
CLAIM_PRICE_MULTIPLER: 7 #The price of a claim would be the distance from one bottom corner, to the opposite top corner multiplied by this number. The default value would make a 5 x 5 claim cost $40 (around there)
CLAIM_BUFFER: 10 #blocks
CLAIM_MINIMUM: 5 #minimum claim would be 5x5 blocks
CLAIM_WORLDS: #players w/o admin perms can only claim in the worlds listed below
  - "world"
CLAIMING_WAND:
  ITEM: "GOLDEN_HOE"
  NAME: "&aClaiming Wand"
  LORE:
    - "&7This is the claiming wand."
    - "&aLeft-click the ground&7 to set the first position."
    - "&aRight-click the ground&7 to set the second position."
    - "&aShift and left-click&7 to claim land after setting points."
    - "&aRight-click the air twice&7 to clear your selection."

