name: Bump Master Branch

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  bump:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4.2.2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@v9
        with:
          github-token: ${{ secrets.github_token }}
          auto-version-bump: false
          auto-version-bump-release: true
      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"